### ISSUE TITLE
global name 'pyodbc' is not defined

### ISSUE THREAD

**Issue by g-sunil** [tosher/TSQLEasy#10]
File "/home/user/.config/sublime-text-3/Packages/TSQLEasy/sqlodbccon.py", line 83, in dbconnect
    except pyodbc.IntegrityError as e:
NameError: global name 'pyodbc' is not defined

TSQLEasy: PyODBC is not available: libodbc.so.1: cannot open shared object file: No such file or directory

But, **pyodbc** is available in the system. 

System Python version 2.6.6.
ST3 (3103)
CentOS 6.7 Release

**Comment by tosher** [comment]
This error exists after installation or after restart too?

P.S. Sublime text not using system python - own version of python, and pyodbc lib inside plugin instead of.

**Comment by g-sunil** [comment]
Hi,

Thank for your reply...

error occurs after installation and also after the restart.

**Comment by tosher** [comment]
You can try to place pyodbc.cpython-33m.so from your system into plugin dir:
```
Packages\TSQLEasy\lib\st3_linux_x64\pyodbc.cpython-33m.so
```
If it will work, then the lib from plugin is incompatible with your OS.
