### ISSUE TITLE
Run sql batch script

### ISSUE THREAD

**Issue by reinaldorauch** [tosher/TSQLEasy#12]
Hi,

How do I run a sql script in batch manner as I would do in SQL Server Management Studio?

Thanks.

**Comment by tosher** [comment]
If you mean *running several statements*:
```sql
statement #1
--go
statement #2
```

**Comment by reinaldorauch** [comment]
I mean like this:
[GO (Transact-SQL)](https://msdn.microsoft.com/en-us/library/ms188037.aspx)
But I was digging on it and it may be something specific to microsoft tools. It would be great if I could run code in the same way that in ssms. I will submit a PR if I can

**Comment by tosher** [comment]
In current version we can to run multi-statement blocks with `--go` as a splitter.

.. and PRs are welcome! :)
