### ISSUE TITLE
Help with another package

### ISSUE THREAD

**Issue by mtxr** [tosher/TSQLEasy#13]
Hello.

I was wondering if you could help me in my package [SQLTools](https://packagecontrol.io/packages/SQLTools)

It's supposed to do de same as yours, but I dont have expertise in MSServer so I hope you could help me.

We could share experiences to make both packages valuable for users.

Hope you agree to join me in this adventure.

[]s.

M.

**Comment by tosher** [comment]
If I can, I will.
What you want to do? :)

**Comment by mtxr** [comment]
I need someone to test the package with MSQLServer params to check if autocomplete and sql executions are ok.

Did you take a look at the package?

**Comment by tosher** [comment]
SQL Server is not supported in current version?

**Comment by mtxr** [comment]
It' is but It's hard to test cause' I'm not familiarized with it
