### ISSUE TITLE
Can I connect to a server using Windows Authentication?

### ISSUE THREAD

**Issue by ledelato** [tosher/TSQLEasy#15]
I'm trying to use TSQLEasy to connect to a server that uses Windows Authentication. I see that this can be done with pyODBC using "Trusted_Connection=yes" rather than a user name and password. Is there a way to use this within the TSQLEasy settings?

Thank you!

**Comment by tosher** [comment]
If Username is empty, trusted connection will be using.

**Comment by ledelato** [comment]
Thanks for the quick response! It's working now.
