### ISSUE TITLE
Using Sublime Text to Connect to SQL Server 

### ISSUE THREAD

**Issue by aglopz** [tosher/TSQLEasy#17]
I have SQL Server installed on my laptop, I only access this on the laptop never remotely from another computer. I have Sublime Text installed and would like to use it to query the SQL Server instance I have running locally. I am having a hard time figuring out how I should connect, you have a previous reply to another thread containing this: 

Preferences -> Package settings -> TSQLEasy -> Settings - User:

    "te_sql_server":
    {
        "Offline":
        {
            "driver": ""
        },
        "Server1":
        {
            "autocommit": true,
            "database": "dbname1",
            "driver": "SQL Server",
            "password": "password1",
            "server": "ip_address1",
            "server_port": "1433",
            "timeout": 1,
            "username": "username1"
        },
        "Server2":
        {
            "autocommit": true,
            "database": "dbname2",
            "driver": "SQL Server",
            "password": "password2",
            "server": "ip_address2",
            "server_port": "1433",
            "timeout": 1,
            "username": "username2"
        }
    }

Since the server is running on my laptop, what settings would I need to use, would a server port still be applicable? as well as the IP address?

I'd like another option other than using the management studio. Thank you in advance.

**Comment by tosher** [comment]
You can try to use this settings for local connection:
```json
"server": "localhost",
"server_port": "1433",
```
or
```json
"server": "127.0.0.1",
"server_port": "1433",
```
