### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by QuinRiva** [tosher/TSQLEasy#19]
I get the following error every time I attempt to run an queries:
[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]Specified SQL Server not found. (6) (SQLDriverConnect)

I'm not entirely sure I have configured the connection appropriately:
```
{
    "te_sql_server":
    {
        "Main": {
            "driver": "SQL Server",
            "server": "serverName\\machine",
            "server_port": 1433,
            "username": "",
            "password": "",
            "database": "dbName",
            "autocommit": true
            }
    }
}
```

The two things I can think that might cause the issue are:
- My server name has a backslash in the name (I've escaped with a second backslash, is this correct?)
- I'm using Windows Authentication, so have left the username and password blank - is this correct?

**Comment by tosher** [comment]
Do you have a connection to port 1433 from your machine? Maybe SQL Server is not listening this port or firewall rules denies connection. What version of SQL server are you using?

About questions - yes, this settings are correct. If username is empty, plugin wil try to connect with option `Trusted_Connection`.

**Comment by msaniie** [comment]
I've run into this same problem. I am using version 10.0.1600. Should I be using a different port?

**Comment by tosher** [comment]
If you have an unnamed instance of the SQL Server, default port is 1433. If you have a named instance and dynamic port, you can try to make settings for server like:

```json
"driver": "SQL Server",
"dsn": "YourServerName",
"server": "",
"server_port": 1433,
```
`server` and `port` settings can has any value and will be skipped, the connection will try to establish by `dsn` option.
 
P.S. Port can be checked on computer by commands:
```
netstat -na
```
and line like
```
  TCP    0.0.0.0:1433            0.0.0.0:0              LISTENING
  # or
  TCP    your.server.ip.address:1433            0.0.0.0:0              LISTENING
```
in answer.

Trying to connect on port:
```
telnet your.server.ip.address 1433
```
If port is open and available for connection (not blocked by firewall or smth.) it will open connection (empty black screen).
