### ISSUE TITLE
join vs Join

### ISSUE THREAD

**Issue by edokan** [tosher/TSQLEasy#23]
Hi,

if I use pascal case join and an alias for joined table using "as" then syntax highlighting fails. if I omit "as" or use lowercase join everything works again.

![image](https://user-images.githubusercontent.com/1482410/48556527-41995700-e8f5-11e8-95d0-d3e72ea63d66.png)

**Comment by tosher** [comment]
Thank you! I'll check and fix it.

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/TSQLEasy/releases/tag/v.1.6.1
