### ISSUE TITLE
connect to sql server with connectionString

### ISSUE THREAD

**Issue by canbax** [tosher/TSQLEasy#24]
Hi Thanks for useful extension

How could I connect to DB ? I have a connection string like
`<add name="MainDatabase" connectionString="Server=YasdaC-NTB; Database=asd; User=asd; Password=asd123; Application Name=asdWeb_English;" />`

**Comment by canbax** [comment]
sorry I should have install pyODBC you can delete this issue

**Comment by tosher** [comment]
Thanks for using the plugin :)
