### ISSUE TITLE
Question: How to configure the connection

### ISSUE THREAD

**Issue by ciceroneves** [tosher/TSQLEasy#25]
I've installed the plugin but I have no idea how to configure the connection to the DB

**Comment by tosher** [comment]
On Windows or Linux/MacOS?

**Comment by ciceroneves** [comment]
Sorry my bad
I am running it on Windows 10

Sending from mobile. Sorry for any typos.

**Comment by tosher** [comment]
Preferences/Package settings/TSQLEasy/Settings, is User settings:

```json
{
	"te_sql_server":
	{
		"MySQLServer":
		{
			"dsn": "",
                        "autocommit": true,
			"database": "mydatabasename",
			"driver": "SQL Server",
			"password": "mypassword",
			"server": "192.168.0.1",
			"server_port": "1433",
			"timeout": 30,
			"username": "sa"
		}
       }
}
```
If your server doesn't have an IP connectivity, you can try to connect by server's name or by DSN from [ODBC Sources](https://docs.microsoft.com/en-us/sql/odbc/admin/managing-data-sources?view=sql-server-2017)
