### ISSUE TITLE
Syntax Highlighting fails on string literals ending in 'on' or ',n'

### ISSUE THREAD

**Issue by ketura** [tosher/TSQLEasy#26]
If the syntax highlighter encounters a string literal (`'foo'`) that is at least 3 characters long and ends in `'on'` or `',n'`, the ending apostrophe will be ignored and all following characters interpreted as part of the string literal (i.e. everything turns green).

Smallest reproduction case: include the string literal `'Jon'` or `'J,n'` in your project file, watch everything turn green.

Real world case:
``` IF NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'Automation')```
everything after this line turns green until the next apostrophe.

EDIT: thinking on this, it looks like recognition for the first apostrophe was copy-pasted to the second apostrophe, which is not correct since the first has to handle the case of `N'foo'`, and the above are edge cases which apply to detecting `N'`.

Incidentally, the comma issue means that there might be something similar lurking for `N''` literals preceded by a comma, tho I am unable to find an example that is syntactically correct.

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/TSQLEasy/releases/tag/v1.6.4

**Comment by ketura** [comment]
Looks like that fixed it.  Thanks!
