### ISSUE TITLE
Sublime Text 3 SQLDriverConnect Error

### ISSUE THREAD

**Issue by ben-sandham** [tosher/TSQLEasy#28]
![image](https://user-images.githubusercontent.com/56902568/96043353-d2a83e00-0e3c-11eb-9db6-85d02e51efe3.png)

Hello, the error above continues to pop up when I am using TSQL package in ST3. Unfortunately, the error popup does not let me copy and paste the error message.

**I am only interested in using the TSQL package as a TSQL syntax highlighter**, not to actually connect to / run queries against a DB with a Microsoft SQL Server connection. 

Please let me know if any system information is required to further troubleshoot this issue.

**Comment by tosher** [comment]
Just set the `driver` option to empty value:
```
       "te_sql_server" {
        "Offline Server": {
            "driver": ""
            }
         }
```
