### ISSUE TITLE
not possible to fire multiple queries in one window

### ISSUE THREAD

**Issue by dreaganluna** [tosher/TSQLEasy#4]
I was happy to see that if I had a part of a window selected that only that part was being executed.
I was less happy to see that when I had more than one statement (an update statement and a select statement) in one window, only the first one would be executed. The result window would say there was no result set, even though certain the select statement should return a result set.

**Comment by tosher** [comment]
You can query more than one statement with separator **--go**
<pre>
select * from table1
--go
select * from table2
</pre>
