### ISSUE TITLE
Executing query does nothing

### ISSUE THREAD

**Issue by joeydrews** [tosher/TSQLEasy#5]
I'm having some issues getting this to work and was hoping for some guidance. I'm running OS X 10.10 and using Sublime Text 3. I installed TSQLEasy using package control with no issues. I set my server information by going to Sublime Text > Preferences > Package Settings > TSQL Easy > Settings - Default. I filled in the information for server, username, password, and database. I go to the command palette and choose TSQL Easy Server Select and choose "Main". From the document type selector in the bottom right hand corner I choose T-SQL. I then start typing code and autocomplete is not showing tables in my database. I typed a simple select statement, highlighted the statement, went back to the command palette an chose TSQL Easy Execute and nothing happens.

Any guidance you can provide will be helpful. Thanks.

**Comment by tosher** [comment]
On current moment, i haven't pyodbc library for OSX :(
You can build your own binary and paste it into plugin

From readme:
<pre>
PyODBC
Now, package includes pyODBC (3.0.7) binaries:
    * Windows: ST2/3 x32/x64
    * Linux: ST2/3 x64
    * Pull requests are welcome! :)
</pre>

**Comment by mkormendy** [comment]
Why not just build the library and add it to the repo?
