### ISSUE TITLE
I can not use

### ISSUE THREAD

**Issue by andersondevelop** [tosher/TSQLEasy#8]
Did the settings, open the console with ctrl + shift + c and choose the database with ctrl + alt + <F11> after it create a query and try to run with ctrl + shift + <F5> and fails.

By sql server managment can connect to this server

My config of the bank is as follows:
{
    "te_sql_server":
    {
        "Main": {
            "driver": "SQL Server",
            "server": "127.0.0.1",
            "server_port": "1433",
            "username": "",
            "password": "",
            "database": "",
            "autocommit": true
            },
        "Offline": {
            "driver": ""
            },
        "SIGE_9999": {
            "driver": "SQL Server",
            "server": "10.0.1.3",
            "server_port": "1433",
            "username": "SIGE_9999",
            "password": "uni4501789",
            "database": "SIGE_9999",
            "autocommit": true
        }
    },
    "te_server_active": "Main",
    "te_encodings":
    {
        "main_profile": "cp1251"
    },
    "te_sql_profile": "main_profile",
    "te_procedure_path": [],
    "te_result_in_new_tab": true,
    "te_show_request_in_result": false
}

**Comment by tosher** [comment]
Do you see some messages in console after trying to execute query (<kbd>F5</kbd>)?
