### ISSUE TITLE
PyODBC is not defined. 

### ISSUE THREAD

**Issue by TigerMint** [tosher/TSQLEasy#9]
After installation on my Ubuntu machine, i am trying to connect to a server but am running into this problem when connecting. It worked on my windows machine without problems. any ideas here?

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./tsqleasy.py", line 496, in run
  File "./tsqleasy.py", line 84, in te_get_connection
  File "./sqlodbccon.py", line 42, in __init__
  File "./sqlodbccon.py", line 72, in dbconnect
NameError: global name 'pyodbc' is not defined

Thanks in advance!
Vin

**Comment by tosher** [comment]
Which Ubuntu version you are using? It's x32 or x64 edition?

**Comment by TigerMint** [comment]
I am x64. When opening ./sqlodbccon.py i get the error of 
TSQLEasy: PyODBC is not available: ./lib/st2_linux_x64/pyodbc.so: undefined symbol: PyUnicodeUCS2_FromObject

is this cause the binaries that come by default are compiled with UCS2 and my system wants to use UCS4 binaries? i tried to replace these binaries with ones i built from the pyodbc source but am running into a whole slew of other problems. 

Thanks for the follow up,
Vin

**Comment by tosher** [comment]
**but am running into a whole slew of other problems**
With the same python version as Sublime text used, and the same pyodbc version?

**Comment by tosher** [comment]
About UCS, i'll try to check pyodbc libs with latest st2/st3 builds.

**Comment by TigerMint** [comment]
Confrimed that alone pyodbc works on my system.

when I replaced the pyodbc.so with other pyodbc binaries (built with python2.7, 3.4 and even with the pyodbc.so used with my other test app) I got this error when opening sqlodbccon.py: 

Reloading plugin /home/tiger/.config/sublime-text-2/Packages/TSQLEasy/sqlodbccon.py
TSQLEasy: PyODBC is not available: ./lib/st2_linux_x64/pyodbc.so: undefined symbol: _PyObject_NextNotImplemented

**Comment by tosher** [comment]
ST2 using python 2.6.5 as i know.

**Comment by TigerMint** [comment]
just tried to built pyodbc with python 2.6.5. didn't get it to work

**Comment by tosher** [comment]
With the same error?

**Comment by TigerMint** [comment]
yeah, used the pyodbc.so built with 2.6.5

./lib/st2_linux_x64/pyodbc.so: undefined symbol: _PyObject_NextNotImplemented

**Comment by tosher** [comment]
Please, check the updated version.
With ubuntu 14.04 x64, st2, unixodbc/freetds on my test machiine works fine.
